name: Python package

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Model Training
        run: |
          python train.py
          python predict.py
      - name: Artefakt speichern
        run: mkdir -p artifacts/artifact
        run: echo hello > artifacts/world.txt
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: artifacts/world.txt